program: /home/eco02/Luc/point-transformer/exp/hand_selected_50%/sweep/train.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
method: bayes
metric:
  goal: maximize
  name: mIoU_val
name: sweep
parameters:
  base_lr:
    values: [ 0.3,0.5,0.7 ]
  freeze_body:
    values: [ True, False ]
  power:
    values: [ 0.3,0.6,0.9 ]
  scheduler:
    values: [ warmup, default ]
  voxel_max:
    values: [5000,10000,15000,20000,25000,30000,35000,40000]
  voxel_size:
    values: [0.04,0.02]
  warmup_length:
    values: [10,25,50]
  weight:
    values: ["",exp/hand_selected_50%/pretrained/model/s3dis_2_class_head.pth]
  weight_decay:
    values: [0.01,0.001,0.0001]
