DATA:
  data_name: church
  data_root:
  test_area: validate
  classes: 2
  fea_dim: 3
  voxel_size: 0.02 # You can leave this blank/none
  voxel_max: 20000 # check this first
  loop: 30 # check this first

TRAIN:
  freeze_body: False
  warmup_length: 25
  power: 0.3
  scheduler: warmup
  arch: pointtransformer_seg_repro
  use_xyz: True
  sync_bn: False
  ignore_label: 255
  train_gpu: [ 0 ]
  workers: 16  # data loader workers
  batch_size: 7  # batch size for training
  batch_size_val: 1  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 100
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.02
  drop_rate: 0.5
  manual_seed: 7777
  print_freq: 1
  save_freq: 1
  save_path:
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1
Distributed:
  dist_url: tcp://localhost:8888
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0

TEST:
  test_list: dataset/s3dis/list/val5.txt
  test_list_full: dataset/s3dis/list/val5_full.txt
  split: val  # split in [train, val and test]
  test_gpu: [0]
  test_workers: 4
  batch_size_test: 4
  model_path:
  save_folder:
  names_path: data/s3dis/s3dis_names.txt
